name: Deploy to Cloudflare Workers

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [main, staging, dev]
    paths:
      - ".github/workflows/cf-deploy.yml"
      - "apps/web/**"
      - "packages/api/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.19.0

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Determine Environment
        id: set-env
        run: |
          if [ "${{ github.base_ref }}" == "main" ]; then
            echo "APP_ENV=production" >> $GITHUB_ENV
          elif [ "${{ github.base_ref }}" == "staging" ]; then
            echo "APP_ENV=staging" >> $GITHUB_ENV
          else
            echo "APP_ENV=development" >> $GITHUB_ENV
          fi

      - name: Build App
        run: pnpm build
        working-directory: apps/web
        env:
          CLOUDFLARE_ENV: ${{ env.APP_ENV }}
          APP_ENV: ${{ env.APP_ENV || 'development' }}

      # Development Environment
      - name: Deploy to Dev
        uses: cloudflare/wrangler-action@v3
        if: github.base_ref == 'dev'
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy --env ${{ env.APP_ENV }}
          workingDirectory: apps/web
        env:
          APP_ENV: ${{ env.APP_ENV }}

      - name: Set secrets for Dev
        if: github.base_ref == 'dev'
        working-directory: apps/web
        run: |
          cat << 'EOF' | npx wrangler secret bulk --name koladae-site-dev
          {
            "RESEND_API_KEY": "${{ secrets.RESEND_API_KEY }}"
          }
          EOF
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      # prod
      - name: Deploy to Prod
        uses: cloudflare/wrangler-action@v3
        if: github.base_ref == 'main'
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy --env ${{ env.APP_ENV }}
          workingDirectory: apps/web
        env:
          APP_ENV: ${{ env.APP_ENV }}

      - name: Set secrets for main
        if: github.base_ref == 'main'
        working-directory: apps/web
        run: |
          cat << 'EOF' | npx wrangler secret bulk --name koladae-site
          {
            "RESEND_API_KEY": "${{ secrets.RESEND_API_KEY }}"
          }
          EOF
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
